CREATE TABLE LOCATION_DIM
(
    LOCATION_DIM_ID NUMBER(*,0) PRIMARY KEY,
    LOCATION_ID VARCHAR2 (36 BYTE),
    LATITUDE NUMBER(*,0),
    LONGITUDE NUMBER(*,0),
    LOCATION_NAME VARCHAR2(30 BYTE),
    COUNTRY VARCHAR2(30 BYTE),
    REGION VARCHAR2(30 BYTE)
);

CREATE SEQUENCE LOCATION_DIM_S;

CREATE OR REPLACE TRIGGER LOCATION_DIM_ON_INSERT
    BEFORE INSERT ON LOCATION_DIM
    FOR EACH ROW
    BEGIN
        :NEW.LOCATION_DIM_ID := LOCATION_DIM_S.NEXTVAL;
    END;
/

CREATE TABLE MILITARY_PERSONNEL_DIM
(
    PERSONNEL_DIM_ID NUMBER(*,0) PRIMARY KEY,
    PERSONNEL_ID NUMBER(*,0),
    NAME VARCHAR2 (25 BYTE),
    SURNAME VARCHAR2 (25 BYTE),
    RANK_NAME VARCHAR2 (25 BYTE),
    AGE NUMBER(*,0)
);

CREATE SEQUENCE PERSONNEL_DIM_S;

CREATE OR REPLACE TRIGGER PERSONNEL_DIM_ON_INSERT
    BEFORE INSERT ON MILITARY_PERSONNEL_DIM
    FOR EACH ROW
    BEGIN
        SELECT PERSONNEL_DIM_S.NEXTVAL
        INTO :NEW.PERSONNEL_DIM_ID
        FROM DUAL;
    END;
/

CREATE TABLE MILITARY_UNIT_DIM
(
    UNIT_DIM_ID NUMBER(*,0) PRIMARY KEY,
    UNIT_ID NUMBER(*,0),
    UNIT_NAME VARCHAR (50 BYTE),
    COMMANDER_ID NUMBER(*,0) FOREIGN KEY REFERENCES MILITARY_PERSONNEL_DIM(PERSONNEL_DIM_ID)
);

CREATE SEQUENCE UNIT_DIM_S;

CREATE OR REPLACE TRIGGER UNIT_DIM_ON_INSERT
    BEFORE INSERT ON MILITARY_UNIT_DIM
    FOR EACH ROW
    BEGIN
        SELECT UNIT_DIM_S.NEXTVAL
        INTO :NEW.UNIT_DIM_ID
        FROM DUAL;
    END;
/

CREATE TABLE ORGANIZATION_DIM
(
    ORGANIZATION_DIM_ID NUMBER(*,0) PRIMARY KEY,
    ORGANIZATION_ID VARCHAR2(36 BYTE),
    ORGANIZATION_DIM_NAME VARCHAR2(30 BYTE),
    ORGANIZATION_DIM_COUNTRY VARCHAR2(30 BYTE)
);

CREATE SEQUENCE ORGANIZATION_DIM_S;

CREATE OR REPLACE TRIGGER ORGANIZATION_DIM_ON_INSERT
    BEFORE INSERT ON ORGANIZATION_DIM
    FOR EACH ROW
    BEGIN
        SELECT ORGANIZATION_DIM_S.NEXTVAL
        INTO :NEW.ORGANIZATION_DIM_ID
        FROM DUAL;
    END;
/

CREATE TABLE AFGHAN_DIM
(
    AFGHAN_DIM_ID NUMBER(*,0) PRIMARY KEY,
    AFGHAN_ID VARCHAR2(36 BYTE),
    NAME VARCHAR2(30 BYTE),
    SURNAME VARCHAR2(30 BYTE),
    GENDER VARCHAR2(30 BYTE),
    ROLE VARCHAR2(30 BYTE),
    AGE NUMBER(*,0),
    ORGANIZATION_ID NUMBER(*,0)
);

ALTER TABLE AFGHAN_DIM ADD FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION_DIM(ORGANIZATION_DIM_ID);

CREATE SEQUENCE AFGHAN_DIM_S;

CREATE OR REPLACE TRIGGER AFGHAN_DIM_ON_INSERT
    BEFORE INSERT ON AFGHAN_DIM
    FOR EACH ROW
    BEGIN
        SELECT AFGHAN_DIM_S.NEXTVAL
        INTO :NEW.AFGHAN_DIM_ID
        FROM DUAL;
    END;
/

CREATE TABLE DATETIME_DIM
(
    DATETIME_DIM_ID NUMBER(*,0) PRIMARY KEY,
    YEAR NUMBER(*,0),
    QUARTER NUMBER(*,0),
    MONTH NUMBER(*,0),
    WEEK NUMBER(*,0),
    DAY NUMBER(*,0),
    HOUR NUMBER(*,0),
    MINUTE NUMBER(*,0)
);

CREATE SEQUENCE DATETIME_DIM_S;

CREATE OR REPLACE TRIGGER DATETIME_DIM_ON_INSERT
    BEFORE INSERT ON DATETIME_DIM
    FOR EACH ROW
    BEGIN
        SELECT DATETIME_DIM_S.NEXTVAL
        INTO :NEW.DATETIME_DIM_ID
        FROM DUAL;
    END;
/


CREATE TABLE GROUP_BRIDGE_DIM
(
    GROUP_DIM_ID NUMBER(*,0) PRIMARY KEY,
    GROUP_ID VARCHAR2(36 BYTE),
    AFGHAN_DIM_ID NUMBER(*,0)
);

ALTER TABLE GROUP_BRIDGE_DIM ADD FOREIGN KEY (AFGHAN_DIM_ID) REFERENCES AFGHAN_DIM(AFGHAN_DIM_ID);

CREATE SEQUENCE GROUP_BRIDGE_DIM_S;

CREATE OR REPLACE TRIGGER GROUP_BRIDGE_DIM_ON_INSERT
    BEFORE INSERT ON GROUP_BRIDGE_DIM
    FOR EACH ROW
    BEGIN
        SELECT GROUP_DIM_ID INTO :NEW.GROUP_DIM_ID
        FROM GROUP_BRIDGE_DIM
        WHERE GROUP_ID = :NEW.GROUP_ID
        AND ROWNUM = 1;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
            :NEW.GROUP_DIM_ID:=GROUP_BRIDGE_DIM_S.NEXTVAL;
    END;
/

CREATE TABLE MILITARY_BRIDGE_DIM
(
    UNIT_DIM_ID NUMBER(*,0),
    PERSONNEL_DIM_ID NUMBER(*,0),
    CONSTRAINT PK_MILITARY_BRIDGE_DIM PRIMARY KEY (UNIT_DIM_ID, PERSONNEL_DIM_ID)
);

ALTER TABLE MILITARY_BRIDGE_DIM ADD FOREIGN KEY (UNIT_DIM_ID) REFERENCES MILITARY_UNIT_DIM(UNIT_DIM_ID);
ALTER TABLE MILITARY_BRIDGE_DIM ADD FOREIGN KEY (PERSONNEL_DIM_ID) REFERENCES MILITARY_PERSONNEL_DIM(PERSONNEL_DIM_ID);

CREATE TABLE ENCOUNTER_DIM
(
    ENCOUNTER_DIM_ID NUMBER(*,0),
    ENCOUNTER_ID VARCHAR2(36 BYTE),
    DATETIME_DIM_ID NUMBER(*,0),
    LOCATION_DIM_ID NUMBER(*,0),
    UNIT_DIM_ID NUMBER(*,0),
    GROUP_DIM_ID NUMBER(*,0),
    NUMBER_OF_AFGHANS NUMBER(*,0),
    NUMBER_OF_MILITARY_PERSONNEL NUMBER(*,0),
    NUMBER_OF_PEOPLE_INVOLVED NUMBER(*,0),
    NUMBER_OF_CIVILIANS NUMBER(*,0),
    NUMBER_OF_CASUALTIES NUMBER(*,0)
);

ALTER TABLE ENCOUNTER_DIM ADD FOREIGN KEY (DATETIME_DIM_ID) REFERENCES DATETIME_DIM(DATETIME_DIM_ID);
ALTER TABLE ENCOUNTER_DIM ADD FOREIGN KEY (LOCATION_DIM_ID) REFERENCES LOCATION_DIM(LOCATION_DIM_ID);
ALTER TABLE ENCOUNTER_DIM ADD FOREIGN KEY (UNIT_DIM_ID) REFERENCES MILITARY_UNIT_DIM(UNIT_DIM_ID);
ALTER TABLE ENCOUNTER_DIM ADD FOREIGN KEY (GROUP_DIM_ID) REFERENCES GROUP_BRIDGE_DIM(GROUP_DIM_ID);

CREATE SEQUENCE ENCOUNTER_DIM_S;

CREATE OR REPLACE TRIGGER ENCOUNTER_DIM_ON_INSERT
    BEFORE INSERT ON ENCOUNTER_DIM
    FOR EACH ROW
    BEGIN
        SELECT ENCOUNTER_DIM_S.NEXTVAL
        INTO :NEW.ENCOUNTER_DIM_ID
        FROM DUAL;
    END;
/